name: 'main'
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Necessary so we have commit history to compare to

      - name: app1 changed in last commit?
        id: changedAction
        uses: Trampoline-CX/action-turbo-changed@v1
        with:
          workspace: app1
          from: HEAD^1 # Check for changes since previous commit (feel free to put a branch name instead)

      - name: Validate Action Output
        if: steps.changedAction.outputs.changed == 'true' # Check output if it changed or not (returns a boolean)
        run: echo 'package-a changed!'
