name: 'main'
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Necessary so we have commit history to compare to

      - name: app1 changed in last commit?
        id: changedAction1
        uses: Trampoline-CX/action-turbo-changed@v1
        with:
          workspace: app1
          from: HEAD^1 # Check for changes since previous commit (feel free to put a branch name instead)

      - name: Validate Action1 Output
        if: steps.changedAction1.outputs.changed == 'true' # Check output if it changed or not (returns a boolean)
        run: echo 'app1 changed!'
        
      - name: app2 changed in last commit?
        id: changedAction2
        uses: Trampoline-CX/action-turbo-changed@v1
        with:
          workspace: app2
          from: HEAD^1 # Check for changes since previous commit (feel free to put a branch name instead)

      - name: Validate Action2 Output
        if: steps.changedAction2.outputs.changed == 'true' # Check output if it changed or not (returns a boolean)
        run: echo 'app2 changed!'
